### ISSUE TITLE
There is no file called pipebatch_minimal.m

### ISSUE THREAD

**Issue by janbrogger** [bwrc/ctap#1]
The README.md indicates that there is a file called pipebatch_minimal.m:

> Getting started
> 
> A minimalistic working example can be found in ~/ctap/templates/minimalistic_example/.
> 
> Copy the cfg_minimal.m and pipebatch_minimal.m files and use them as a starting point for your own pipe.

OBSERVED: A file called pipebatch_minimal.m exists under ~/ctap/templates/minimalistic_example/
EXPECTED: No such file exists

**Comment by jutako** [comment]
I apologize that the documentation is not totally in-sync. I believe the correct file is:
https://github.com/bwrc/ctap/blob/master/ctap/templates/minimalistic_example/runctap_minimal.m

**Comment by zenBen** [comment]
README is updated.
