### ISSUE TITLE
Test branch dev against any ongoing work and merge to master

### ISSUE THREAD

**Issue by jutako** [bwrc/ctap#10]
I rsynced the current state of ctap_dev (11.10.2017) onto public ctap branch dev. Users may now checkout branch dev and see how much breaks upon this update. Once all relevant ongoing projects have been updated to work with ctap::dev it may be merged into master. At FIOH we work with ctap_dev (which is now the same as ctap::dev).

The sync (just to be exact):
inpath=/home/jkor/work_local/projects/ctap/ctap_pipeline/ctap/
outpath=/home/jkor/work_local/projects/ctap/ctap_public/ctap/
rsync -avzbc --suffix=_bkp-`date +%Y-%m-%d_%H-%M-%S` --exclude="doc" --exclude=".git" --exclude="*.m~" --backup-dir=$bkppath --delete  $inpath $outpath

inpath=/home/jkor/work_local/projects/ctap/ctap_pipeline/dependencies/
outpath=/home/jkor/work_local/projects/ctap/ctap_public/dependencies/
rsync -avzbc --suffix=_bkp-`date +%Y-%m-%d_%H-%M-%S` --exclude=".git" --backup-dir=$bkppath --delete  $inpath $outpath

**Comment by jutako** [comment]
I really recommend that you test your existing analyses using ctap/dev:

git fetch --all
git checkout dev

and you should be able to test. If master contains changes you need, you can rebase dev to include those:
git checkout dev
git rebase master

I would like to merge ctap/dev shortly into ctap/master to get rid of a private ctap_dev repo and keep developing only in public ctap (this repo).

**Comment by zenBen** [comment]
Now pushed rsync'ed updates from ctap_dev::hydra to ctap::dev, according to your instructions (separate rsyncs for ctap_dev/ctap and ctap_dev/dependencies).

Checked status of changes with git diff. Major changes mentioned in commit message - but mostly in HYDRA specific functions. Also added several large EEG files for HYDRA. I am using git LFS for these, but they may cause a slowness if you pull. 

I will check ctap::dev performance against my analysis pipes tomorrow or asap.

**Comment by zenBen** [comment]
Yeah git LFS was not enabled on first commit so had to commit and push again to get it done right. Tracking all *.mat, *.set, *.fdt files. Enable LFS to handle those large files.

**Comment by zenBen** [comment]
Now tracking all *.mat, *.set, *.fdt files. Enable LFS to handle those large files.
