### ISSUE TITLE
ctapeeg_reref_data.m is not in repo but called

### ISSUE THREAD

**Issue by jutako** [bwrc/ctap#11]
It seems that ctapeeg_reref_data.m is at some point moved to deprecated functions (does not exist in master or dev but found in on my local machine), but calls to it still remain in ctapeeg_detect_bad_channels.m. How did this happen?

**Comment by zenBen** [comment]
I suppose the dependency was missed because the deprecated folder (with ctapeeg_reref_data.m) was on the path when we were still working on ctap_dev.

**Comment by zenBen** [comment]
Not sure why it was deprecated, seems to be a useful way to handle ambiguity in the reference specification.
