### ISSUE TITLE
Issues getting started

### ISSUE THREAD

**Issue by janbrogger** [bwrc/ctap#2]
REPRO
Windows 7, Matlab 2017a
1. Clone the repo
>     git clone https://github.com/bwrc/ctap J:\CTAP\
2. Add the CTAP path to matlab by executing 
>     addpath('J:\CTAP\')
3. I copied the folder 
>    J:\CTAP\ctap\templates\minimalistic_example 

to 
>    J:\CTAP\ctap\templates\jan-example
4. Change directory
> cd J:\CTAP\ctap\templates\jan-example
5. Execute a CTAP run
>     runctap_minimal()
OBSERVED:
> Error in runctap_minimal (line 23)
> MC = path2measconf(data_dir_out, '*.set');

EXPECTED: 
Something to happen

6. Tried to fix path by doing:
> addpath(genpath('J:\CTAP\'))
7. Then executing
>     runctap_minimal()

OBSERVED:
> Reference to non-existent field 'measurement'.
> 
> Error in get_measurement_id (line 2)
> MeasSub = struct_filter(MC.measurement, Filt);
> 
> Error in runctap_minimal (line 30)
> Cfg.pipe.runMeasurements = get_measurement_id(Cfg.MC, Filt);
> 

EXPECTED: 
Something to happen

**Comment by zenBen** [comment]
Hello,
this is an issue with the instructions. The `runctap_minimal` script expects to find seed data with which to generate a synthetic dataset and process it. The seed data is stored in the repo, under `ctap\\data`. To access it, the script uses a relative path (line 13):
`data_dir_seed = fullfile(cd(),'ctap','data');`

Thus, Matlab's present working directory `pwd` must point to the root of the ctap repository when the script is called (not to your example directory).

To build your example project in the directory you prefer, you can edit line 4 in `runctap_minimal`, e.g.:
`project_dir = fullfile(cd(), 'ctap', 'templates' , 'jan-example');`

Notify if this works and I will close.
