### ISSUE TITLE
Cfg.env.logFile should not be defined by user!

### ISSUE THREAD

**Issue by jutako** [bwrc/ctap#23]
Stumbled upon a non-intended behavior that occurs when the user has set the Cfg.evn.logFile manually and is using ctap_pipeline_brancher.m: the log becomes huge very fast (e.g. 1.5Gb of text for a single measurement test run). The reason are the lines

myReport(sprintf('\n================\nBADNESS SUMMARY:\n'), Cfg.env.logFile);
myReport(scrape_file_for_str(Cfg.env.logFile, 'Bad '), Cfg.env.logFile);

which assume that Cfg.env.logFile is small and changes frequently. If Cfg.env.logFile stays fixed, this creates a vicious recursive cycle that results in exponential growth of log file rows ...

**Comment by zenBen** [comment]
Interesting! Would be ideal to separate the global log file from the log of recent run, which is to be scraped for a summary. Local log can then be protected/dynamic, and global log can be user-defined. I'd offer to look into it but I have a baby coming any day now!

**Comment by zenBen** [comment]
Implemented a simple file swapping fix for this, where if user does define `Cfg.env.logFile`, then that file is reassigned to  `Cfg.env.userLogFile`, and `Cfg.env.logFile` is created as a timestamped txt file as per normal. 

The contents of `Cfg.env.logFile` are then written to the user defined file  `Cfg.env.userLogFile`, as one of the closing operations of `CTAP_pipeline_looper()` or `CTAP_pipeline_brancher()`
