### ISSUE TITLE
Wiki has pages missing

### ISSUE THREAD

**Issue by janbrogger** [bwrc/ctap#3]
The [main wiki page](https://github.com/bwrc/ctap/wiki) lists 11 other Wiki pages, but all of the links give a 404 error.

**Comment by jutako** [comment]
I cannot verify that all of them would be broken. Some indeed seem to point to a private development version of the repo and these return 404 error for a non-authorized user. We will fix these.

**Comment by zenBen** [comment]
Yes development version links crept back into the wiki after an earlier update from the private repo. Now fixed.
